#spring:
 # application:
  #  name: dept-service
  #config:
   # import: optional:configserver:http://localhost:8888

  
spring:
  application:
    name: dept-service
  jpa:
    show-sql: true  # Shows the SQL queries in the logs
    hibernate:
      ddl-auto: update  # Automatically updates the schema based on entity changes
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL dialect for Hibernate
  datasource:
    url: ${DB_URL}  # MySQL connection URL
    username: ${DB_USERNAME}  # MySQL username (replace if different)
    password: ${DB_PASSWORD}  # MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver

server:
  port: 8085  # Your server's port
